theme: minima
title: the luckylogan blog
author: luckylogan
email: loganjamesy@outlook.com
description: > # this means to ignore newlines until "baseurl:"
a educational beginners blog

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  luckylogan # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
